# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'system/kpmcore': '@same'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
    'system/kpmcore': '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
